const  FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
const  FETCH_DATA_FULFILLED = 'FETCH_DATA_FULFILLED';
const  FETCH_DATA_REJECTED = 'FETCH_DATA_REJECTED';
export {FETCH_DATA_FULFILLED, FETCH_DATA_PENDING, FETCH_DATA_REJECTED}
